// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuIXDHx_7WyKedGeUVz6n59HXI-ZqcdWU',
    appId: '1:647078749532:ios:3c0bdfa53696d668d84d99',
    messagingSenderId: '647078749532',
    projectId: 'solar-cleaning-app-6409f',
    storageBucket: 'solar-cleaning-app-6409f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFGqk5eVoA_3IOnePAqpPdNOZ0_-CDPpo',
    appId: '1:647078749532:web:d291d20fb66a7fc1d84d99',
    messagingSenderId: '647078749532',
    projectId: 'solar-cleaning-app-6409f',
    authDomain: 'solar-cleaning-app-6409f.firebaseapp.com',
    storageBucket: 'solar-cleaning-app-6409f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBicgPws4z3BZll7k8EDlq0wbAZE4cB3n8',
    appId: '1:647078749532:android:b99ffe3e8db934f5d84d99',
    messagingSenderId: '647078749532',
    projectId: 'solar-cleaning-app-6409f',
    storageBucket: 'solar-cleaning-app-6409f.firebasestorage.app',
  );

}